### ISSUE TITLE
Some questions regarding the testing process

### ISSUE THREAD

**Issue by guwenxiang1** [ShuweiShao/IEBins#1]
Thank you for the excellent work you have done.

I encountered the following issue when running 'python iebins/eval.py configs/arguments_eval_kittieigen.txt. 
The specific information is as follows.

(midas-py310) ouc@ouc:/data2/gwx/MonoDepthEst/IEBins$ python iebins/eval.py configs/arguments_eval_kittieigen.txt
/home/ouc/anaconda3/envs/midas-py310/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1666642969563/work/aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
== Load encoder backbone from: None
== Total number of parameters: 272927893
== Total number of learning parameters: 272927893
== Model Initialized
== Loading checkpoint '/data2/gwx/MonoDepthEst/IEBins/model_zoo/kittieigen_L.pth'
== Loaded checkpoint '/data2/gwx/MonoDepthEst/IEBins/model_zoo/kittieigen_L.pth'
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 305/305 [00:03<00:00, 82.94it/s]
Computing errors for 0 eval samples , post_process:  True
  silog, abs_rel,   log10,     rms,  sq_rel, log_rms,      d1,      d2,      d3
    nan,     nan,     nan,     nan,     nan,     nan,     nan,     nan,     nan

These are some parameters.
--data_path_eval /data2/gwx/MonoDepthEst/rock_garden2/imgs/LFT
--gt_path_eval /data2/gwx/MonoDepthEst/rock_garden2/depth/disparity_LFT
--filenames_file_eval /data2/gwx/MonoDepthEst/VA-DepthNet/data_splits/flsea.txt

The test dataset has been cropped to match the size of KITTI.
Each line in the txt file contains two file names, one is the img file and the other is the corresponding depth file.

 Excuse me, do you know where the problem lies?

**Comment by ShuweiShao** [comment]
Thank you for your attention. If you can reproduce the results on the KITTI dataset? Which depth range of GT from your custom data lies in ?

**Comment by guwenxiang1** [comment]
I have also conducted identical tests on VA-DepthNet. Before conducting the test, I gathered statistics on the maximum depth, minimum depth, and average depth in the depth map, and the outcomes are as follows:

 Computing errors for 305 eval samples , post_process:  False
  silog, abs_rel,   log10,     rms,  sq_rel, log_rms,      d1,      d2,      d3
18.3173, 720.0839,  2.8449,  4.7641, 3406.9543,  6.5532,  0.0000,  0.0000,  0.0000

I am a beginner in this field.I have downloaded all the monocular datasets related to KITTI, but it seems that the downloaded dataset does not match the file directories mentioned in the txt file.

![image](https://github.com/ShuweiShao/IEBins/assets/43127637/0ddf0614-517b-428e-928e-7a988a10df63)
How should I proceed with testing the KITTI dataset?

**Comment by ShuweiShao** [comment]
It seens that the results of VA-DepthNet are also terrible. Have you visualized the predicted depth before? You can prepare the kitti dataset by downloading the raw data and the correspording ground-truth. You may refer to https://github.com/cleinc/bts.

**Comment by guwenxiang1** [comment]
I have downloaded the three datasets shown in the figure. However, upon my observation, it appears that their file structure does not match the file directory mentioned in the accompanying text file. 
![image](https://github.com/ShuweiShao/IEBins/assets/43127637/ebf1e9cc-4aa8-4ea2-a84b-1394c08246c6)
One possible reason for the poor depth results could be that this dataset is an underwater monocular depth dataset.Indeed, such poor performance is unexpected. The dataset in question reportedly has an average depth mean of around 2.5. 
![image](https://github.com/ShuweiShao/IEBins/assets/43127637/383e1f65-4e1d-481f-b8c7-79a55bab93ff)
and GT is : 
![image](https://github.com/ShuweiShao/IEBins/assets/43127637/4748e77c-1e13-4038-bdbf-0c2250e93250)
Thank you for your help!!

**Comment by ShuweiShao** [comment]
You could reorganize the data structure to match the file directory  in the training text file.

**Comment by guwenxiang1** [comment]
Dear ShuweiShao, When I was fine-tuning the model using my own dataset, I encountered the following error:


Traceback (most recent call last):
  File "/data2/gwx/MonoDepthEst/IEBins/iebins/train.py", line 499, in <module>
    main()
  File "/data2/gwx/MonoDepthEst/IEBins/iebins/train.py", line 493, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/home/ouc/anaconda3/envs/midas-py310/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/ouc/anaconda3/envs/midas-py310/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/ouc/anaconda3/envs/midas-py310/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/ouc/anaconda3/envs/midas-py310/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/data2/gwx/MonoDepthEst/IEBins/iebins/train.py", line 320, in main_worker
    optimizer.step()
  File "/home/ouc/anaconda3/envs/midas-py310/lib/python3.10/site-packages/torch/optim/optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File "/home/ouc/anaconda3/envs/midas-py310/lib/python3.10/site-packages/torch/optim/optimizer.py", line 23, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/home/ouc/anaconda3/envs/midas-py310/lib/python3.10/site-packages/torch/optim/adam.py", line 234, in step
    adam(params_with_grad,
  File "/home/ouc/anaconda3/envs/midas-py310/lib/python3.10/site-packages/torch/optim/adam.py", line 300, in adam
    func(params,
  File "/home/ouc/anaconda3/envs/midas-py310/lib/python3.10/site-packages/torch/optim/adam.py", line 363, in _single_tensor_adam
    exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)
RuntimeError: The size of tensor a (4) must match the size of tensor b (7) at non-singleton dimension 3


Do you know what the reason is? Thank you.

**Comment by ShuweiShao** [comment]
It seems that the size mismatch at dimension 3 between tensor a and tensor b.

**Comment by Wujinnanqqqqqq** [comment]
> Thank you for the excellent work you have done.
> 
> I encountered the following issue when running 'python iebins/eval.py configs/arguments_eval_kittieigen.txt. The specific information is as follows.
> 
> (midas-py310) ouc@ouc:/data2/gwx/MonoDepthEst/IEBins$ python iebins/eval.py configs/arguments_eval_kittieigen.txt /home/ouc/anaconda3/envs/midas-py310/lib/python3.10/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /opt/conda/conda-bld/pytorch_1666642969563/work/aten/src/ATen/native/TensorShape.cpp:3190.) return _VF.meshgrid(tensors, **kwargs) # type: ignore[attr-defined] == Load encoder backbone from: None == Total number of parameters: 272927893 == Total number of learning parameters: 272927893 == Model Initialized == Loading checkpoint '/data2/gwx/MonoDepthEst/IEBins/model_zoo/kittieigen_L.pth' == Loaded checkpoint '/data2/gwx/MonoDepthEst/IEBins/model_zoo/kittieigen_L.pth' 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 305/305 [00:03<00:00, 82.94it/s] Computing errors for 0 eval samples , post_process: True silog, abs_rel, log10, rms, sq_rel, log_rms, d1, d2, d3 nan, nan, nan, nan, nan, nan, nan, nan, nan
> 
> These are some parameters. --data_path_eval /data2/gwx/MonoDepthEst/rock_garden2/imgs/LFT --gt_path_eval /data2/gwx/MonoDepthEst/rock_garden2/depth/disparity_LFT --filenames_file_eval /data2/gwx/MonoDepthEst/VA-DepthNet/data_splits/flsea.txt
> 
> The test dataset has been cropped to match the size of KITTI. Each line in the txt file contains two file names, one is the img file and the other is the corresponding depth file.
> 
> Excuse me, do you know where the problem lies?

您好我想请问一下您是如何将评价指标的nan改掉的
