### ISSUE TITLE
prediction - fusion technique

### ISSUE THREAD

**Issue by PetropoulakisPanagiotis** [ShuweiShao/IEBins#11]
Hi, 

I saw that by default you use a fusion technique where you combine the depth prediction with the depth prediction of the "horizontal flipped image".

The results in the paper use this technique too? What is the drop in performance if you remove this step? 

Thank you in advance!

**Comment by ShuweiShao** [comment]
Yes, we follow adabins and newcrfs, which also use this technique. When removing it, the preformance will suffer a slight drop.
