### ISSUE TITLE
感谢作者的优秀工作，我在用nyu-T.pth的时候，出现了错误，似乎是nyu-T.pth与model的size不匹配

### ISSUE THREAD

**Issue by WilliamOChai** [ShuweiShao/IEBins#12]
感谢作者的优秀工作，我在用nyu-T.pth的时候（nyu-L.pth是正常工作的），出现了错误，似乎是nyu-T.pth与model的size不匹配，修改encoder的base07和large07没有起作用。
module.backbone.layers.2.blocks.16.attn.relative_position_index", "module.backbone.layers.2.blocks.16.attn.qkv.weight", "module.backbone.layers.2.blocks.16.attn.qkv.bias", "module.backbone.layers.2.blocks.16.attn.proj.weight", "module.backbone.layers.2.blocks.16.attn.proj.bias", "module.backbone.layers.2.blocks.16.norm2.weight", "module.backbone.layers.2.blocks.16.norm2.bias", "module.backbone.layers.2.blocks.16.mlp.fc1.weight", "module.backbone.layers.2.blocks.16.mlp.fc1.bias", "module.backbone.layers.2.blocks.16.mlp.fc2.weight", "module.backbone.layers.2.blocks.16.mlp.fc2.bias", "module.backbone.layers.2.blocks.17.norm1.weight", "module.backbone.layers.2.blocks.17.norm1.bias", "module.backbone.layers.2.blocks.17.attn.relative_position_bias_table", "module.backbone.layers.2.blocks.17.attn.relative_position_index", "module.backbone.layers.2.blocks.17.attn.qkv.weight", "module.backbone.layers.2.blocks.17.attn.qkv.bias", "module.backbone.layers.2.blocks.17.attn.proj.weight", "module.backbone.layers.2.blocks.17.attn.proj.bias", "module.backbone.layers.2.blocks.17.norm2.weight", "module.backbone.layers.2.blocks.17.norm2.bias", "module.backbone.layers.2.blocks.17.mlp.fc1.weight", "module.backbone.layers.2.blocks.17.mlp.fc1.bias", "module.backbone.layers.2.blocks.17.mlp.fc2.weight", "module.backbone.layers.2.blocks.17.mlp.fc2.bias". 
	Unexpected key(s) in state_dict: "module.crf3.proj_x.weight", "module.crf3.proj_x.bias", "module.crf2.proj_x.weight", "module.crf2.proj_x.bias", "module.crf1.proj_x.weight", "module.crf1.proj_x.bias". 
	size mismatch for module.update.gru.convz1.weight: copying a param with shape torch.Size([128, 480, 1, 5]) from checkpoint, the shape in current model is torch.Size([128, 512, 1, 5]).
	size mismatch for module.update.gru.convr1.weight: copying a param with shape torch.Size([128, 480, 1, 5]) from checkpoint, the shape in current model is torch.Size([128, 512, 1, 5]).
	size mismatch for module.update.gru.convq1.weight: copying a param with shape torch.Size([128, 480, 1, 5]) from checkpoint, the shape in current model is torch.Size([128, 512, 1, 5]).
	size mismatch for module.update.gru.convz2.weight: copying a param with shape torch.Size([128, 480, 5, 1]) from checkpoint, the shape in current model is torch.Size([128, 512, 5, 1]).
	size mismatch for module.update.gru.convr2.weight: copying a param with shape torch.Size([128, 480, 5, 1]) from checkpoint, the shape in current model is torch.Size([128, 512, 5, 1]).
	size mismatch for module.update.gru.convq2.weight: copying a param with shape torch.Size([128, 480, 5, 1]) from checkpoint, the shape in current model is torch.Size([128, 512, 5, 1]).
	size mismatch for module.backbone.patch_embed.proj.weight: copying a param with shape torch.Size([96, 3, 4, 4]) from checkpoint, the shape in current model is torch.Size([128, 3, 4, 4]).

**Comment by ShuweiShao** [comment]
hi，nyu-T.pth的encoder是用的swin-tiny, 修改成tiny07试试呢

**Comment by WilliamOChai** [comment]
好的，修改之后已经解决，非常感谢！
