### ISSUE TITLE
nyu training 

### ISSUE THREAD

**Issue by PetropoulakisPanagiotis** [ShuweiShao/IEBins#14]
For evaluation at NYU, you have used the dataset from here (https://github.com/cleinc/bts/tree/master/pytorch) and you evaluate on the "rawDepths" (see also here: https://cs.nyu.edu/~silberman/datasets/nyu_depth_v2.html).

During training, the depth maps are again of the type "rawDepths", or do you use the pre-processed dense depths from NYU?
(From the site of NYU: In addition to the projected depth maps, we have included a set of preprocessed depth maps whose missing values have been filled in using the [colorization scheme of Levin et al](http://www.cs.huji.ac.il/~yweiss/Colorization/)

Thank you in advance.

**Comment by ShuweiShao** [comment]
Hi, please also see https://github.com/cleinc/bts/tree/master/pytorch to prepare the training dataset. The ground-truth depth maps used in our training are not dense.

**Comment by PetropoulakisPanagiotis** [comment]
Thank you,
