### ISSUE TITLE
Some questions about the training on the Kitti official datasets

### ISSUE THREAD

**Issue by Guzaiwang** [ShuweiShao/IEBins#2]
Hi, thanks for your excellent work.

Could you share the training scripts on the Kitti official dataset, including the validation and test settings?

**Comment by ShuweiShao** [comment]
Thanks for your attention. We will add these details in an update as suggested. Perhaps you can refer to the official newcrfs github to modify the settings for urgent need.

**Comment by ShuweiShao** [comment]
Hi, the training, validation and test settings on the KITTI official split has been added.
