### ISSUE TITLE
Postprocessing

### ISSUE THREAD

**Issue by dmariaa** [ShuweiShao/IEBins#22]
Hi!! 

I am testing my outdoor driving synthetic dataset with dense ground truth depth. I have trained your model with the training data of my dataset. Now I am evaluating the model trained on the synthetic dataset using the KITTI eigen evaluation data.

I have modified your scripts (training, evaluation, inference) to accept my dataset and realized that you post-process the result depth map in all of them, but can't find references in your paper about this optimization. Can you help me understand the need for it?

```python
pred_depth = post_process_depth(pred_depths_r_list[-1], pred_depths_r_list_flipped[-1])
``` 

Kind regards and thanks for your work.

**Comment by ShuweiShao** [comment]
Hi, this is a test time augmentation techinique borrowed from NeWCRFs.
