### ISSUE TITLE
load encoder - warnings 

### ISSUE THREAD

**Issue by PetropoulakisPanagiotis** [ShuweiShao/IEBins#4]
It this normal behavior from your side? 

Script to run: python iebins/train.py configs/arguments_train_kittieigen.txt

== Load encoder backbone from: models/swin_tiny_patch4_window7_224_22k.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: norm.weight, norm.bias, head.weight, head.bias, layers.0.blocks.1.attn_mask, layers.1.blocks.1.attn_mask, layers.2.blocks.1.attn_mask, layers.2.blocks.3.attn_mask, layers.2.blocks.5.attn_mask

missing keys in source state_dict: norm0.weight, norm0.bias, norm1.weight, norm1.bias, norm2.weight, norm2.bias, norm3.weight, norm3.bias

**Comment by ShuweiShao** [comment]
Hi, you can just ingore it.
